### ISSUE TITLE
AttributeError: 'ConvSN2DTranspose' object has no attribute 'output_padding'

### ISSUE THREAD

**Issue by zoeleeee** [IShengFang/SpectralNormalizationKeras#2]
I import your ConvSN2DTranspose from SpectralNormalizationKeras in my code
but I met the error in line 609: if self.output_padding is None:
AttributeError: 'ConvSN2DTranspose' object has no attribute 'output_padding'
my keras version is 2.2.0
Have you met this problem? 
Is it the issue of keras version?

**Comment by IShengFang** [comment]
Hi @zoeleeee 

My environment is as below,
Keras==2.2.2
tensorflow-gpu==1.10.1

The code is worked on my environment.

Best,
