### ISSUE TITLE
Typos and training stuck while using gradient penalty

### ISSUE THREAD

**Issue by VincieD** [IShengFang/SpectralNormalizationKeras#3]
Hi guys,
i've downloaded you code and tried out. But I quickly figured out, that there are some typos. For instance:
line 137  in CIFAR_SNGAN.py -  BATCH_SIZE instead of BATCHSIZE
,which leads me to the question if you ever tried the code with gradient penalty turned on.

Because after fixing this typo the training doesn't start at all and stuck on the estimating time - and doesn't move on even after 2 hours.

Thank you,
Vaclav

**Comment by IShengFang** [comment]
Hi @VincieD ,

I fixed this bug
These two lines are dependence
```
            weights = K.random_uniform((BATCH_SIZE, 1, 1, 1))
```
```
    dummy_y = np.zeros((BATCH_SIZE, 1), dtype=np.float32)
```

Thanks,
I-Sheng Fang

ref:
https://github.com/IShengFang/SpectralNormalizationKeras/blob/7459c9093aa35e8f85ed15394b89255b2fc3dc28/CIFAR10_SNGAN.py#L136
https://github.com/IShengFang/SpectralNormalizationKeras/blob/7459c9093aa35e8f85ed15394b89255b2fc3dc28/CIFAR10_SNGAN.py#L220
